[project]
name = "agentic-sim"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "databricks-connect (==16.4.19)",
    "torch (>=2.13.0,<3.0.0)",
    "pytest (>=9.1.1,<10.0.0)"
]

[project.scripts]
train_agents = "agentic_sim.workflows.tasks.task_train_agents:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ipykernel (>=7.3.0,<8.0.0)"
]
